FROM --platform=linux/amd64 alpine/git

RUN apk add --no-cache bash

WORKDIR /assets

COPY sync-script.sh .

RUN chmod +x sync-script.sh

WORKDIR /app

ENTRYPOINT ["/bin/bash", "-c", "/assets/sync-script.sh"]
